sudo: false
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- openjdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
- ./travis-build-pr.sh
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then bash ./travis-build.sh; fi
env:
  global:
  - secure: XoyvnsN30AzcOF4Tx2rXLmFXTixNwM53TTKKV4iXnoLU/E+aIyQ1TjOvPiJTpF1WPHGAgqvQdy0qvxErIjSLBDfbmItkMhdOLkIXEW33GT6zLfqwqP4+quRYNN6bF7lUhmu9vdi8m5hWrhzxigPAGlxM/Fwppxo4Sr6iDeuNxbkJ+6lAK1he7wA7V0n6TOIXJV7hPCf4pBIMPWMQ45UxYcN2oBgNzU3664XEwoOjjx1xQKctlSyzLxf3xhKtEhELkF0eGMx24IcCXaXFEQTpFZNcOuwPGt+wujTivEgPu7zqCWbcvlC9G4iVtdzUoOkm9wnu5dDgE3fzyTFPW+gM+AtB5ddrGWqSObOJDDYsjsaMuHuagAwE4jyBfcssrT2yi8ymlE3jGEoxYBkA1pv90w8e5S4BQMInk/oGYQrGmYJ1nSUppTE5Kpcm2qQJq6uoRVcVMHR2/NQIdOe2QKwHcWbrkThFOCM4fJARyhdNj8Lz5jZ4IoYzCmHPtUFcK3t5PZpkDETZLpcGCyXwHAtt0kjED0G/gtJY78Iu8v4C0zd32wzJno8PRlYO5bfxEPsJ0gm8w8Pa1r9Bvnf7C0sNXzTQHOmDHgpZTYR+7cpmsTWczgMSXqycWmLV492k8bo2FDKuYjtRRfEw9QRCQnBY4+6cz4RJTMGOtluHpOOXVzQ=
  - secure: JY/DExvSCJXrSa2/eUp1IB9SczdlQxQmobY98P7LNyfsl31kAJveU8qMxe4W/elkOwsB/hsrWZVd6FgXH6e3AfZ18JoPIDPXUH3HJr/CjAIjc10peJOKQ8CzuQJS8Lpj+TqAgXMxjqRKdhnJ01BZifPpyfy6CbgwGQwgVEjfj5vwwFwrrCyb2vnzl7Qz4P5IuCGxSPCG493nLt72nMJyCunuvAjd51OBP6G5sxjmLIjdITGylec0Xlb594dxuFMLSZl0pN1rUTwn46tAsyoK2UwqB7Wy41ThE9tOqYRTxb0SstJpnyHm6HWj/aNz6AoamL4o1sVkEnuc/xWaF04srFc2gzF5Owy7CTyhCdKGRiiRR4S5jLijo4+R/cx8kkdy0K3iJL6xiPeTZQ22oqZgsvaz/zOXjEHYH3Dwyy7qnXeuxKJw7Zx3xR6ndCDoFEADNNwjEOOyrwsIDZoKxAXaNYR6n01TxUxF4aaUDN1hWOWAOEr2r9Odt53XcPF64C47e6qGxKzfIagwm34/8Fx7WJdKsFNX5xYjEM7j0gYrVHOC4RA1MBPVmk5l4nyCpC8QkHxHzdhLQT7IZR9mm2tfy7kZPo9tV9s5FqBr646rX7WDDGH0B8qFjBTCvf77TsDaqW9WXB0xSKKUtVY88o8JN5FwkDis8zu1714IQXsh7hA=
  - secure: c08sIt2uzPECxu2ldbCaB7E2DdyIevaG+gvc2bgizL35sevENMfdnKabe2jCFRyNq2jtSG5YqAJ5ZF5J68h8jf4d03q2U7mVGzjGK/9Zmy0xjMBpLVdsbb4oxstjwuIfTjdjPO5xpYiX1n9avgs7dQTJbSZVXFL+enU1RehATSM0HFfZtAQp/BAYxo0rlKkSYaTqK8Y+Leg30kYnmNsqjTVa/+JF2kIu4hOzk2ceFCXazRvaKfNEPzLAv1rJzUZ7dN9dBt0gCwyuV9AE89y0ENu2esH1S+zOCxykLf2BmLI6uXpk8MOr8VyUNN+Zp1quSezrelyqRP/Qg/5JVEXAZ1lmZZtrA/eaI8glgYYh3j3AucexCD3HqLVFv6IG+9fm8IFE61+Wqh2w+9gmbhfqGRo2/vO6yND8TcTzecKWFOW+6xZO/jNyPgX3OrURCjecHuG+ZJsYN3jIN25Imn+DfIOj0gHL6DvG1IQ49ebSI+XC41dpDk/NHQn+5r3KnUowAVEsPr0tXxtydEt6gnr1baUVDDZkXqRbWCJhGUMoWzNnDDnU/p+ifHlRlxhbqOso2awpJt1fpm2LcWC+GWC+TjotaiYKjiEiAdrLMm/KPJ+MQv/Q9Kb5OdGOoWaBgYthI40ZlMpyw2ONGAEC0H7XhNDSeybvalNRvA3OPA8AXys=
