#tag::micronaut[]
micronaut:
    application:
        name: example.micronaut
    server:
        port: 8080
    http:
        client:
            read-timeout: 10s
#end::micronaut[]
#tag::awsapigateway[]
awsapigateway:
    stage: "beta"
    vatinvokeurl: "https://8ah5p89xof.execute-api.eu-west-3.amazonaws.com"
#end::awsapigateway[]
#tag::vat[]
vat:
    percentage: 0.21
    scale: 2
    retry:
        attempts: 5
        delay: 5s
#end::vat[]
#tag::aws[]
aws:
    lambda:
        functions:
            vat:
                functionName: vies-vat-validator
                qualifer: vat
        region: eu-west-3 # Paris Region
#end::aws[]
